# Generated by Django 4.0.4 on 2022-08-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='produto',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='variacao',
            name='preco_promocional',
        ),
        migrations.AlterModelTable(
            name='produto',
            table=None,
        ),
    ]
