# Generated by Django 4.0.4 on 2022-08-13 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(blank=True, max_length=70)),
                ('descricao', models.TextField(blank=True)),
                ('telefone', models.CharField(max_length=100)),
                ('salario', models.FloatField(default=0)),
                ('data_admissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
                'ordering': ['nome'],
                'managed': True,
                'unique_together': {('nome', 'sobrenome')},
                'index_together': {('nome', 'sobrenome')},
            },
        ),
    ]
